### ISSUE TITLE
Is still works? 

### ISSUE THREAD

**Issue by Jimmi08** [wpsight/wpcasa-list-agents#2]
Maybe PHP 7.2 is problem, but not options are added in dashboard after activation. I tried your demo and agencies with agents are not there. 
Thanks

**Comment by JoeHana** [comment]
This plugin does not have any options included. It only provides a shortcode for displaying all agents on a page. Please check [here](https://wpcasa.com/downloads/wpcasa-list-agents/) for more informations on that.
